// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZUJY-FE7peeFIpCWAxEsLQlzcMEdRc_o',
    appId: '1:1075523292633:web:f50c5d17d9e42afd9e5dc8',
    messagingSenderId: '1075523292633',
    projectId: 'chuende2acc',
    authDomain: 'chuende2acc.firebaseapp.com',
    storageBucket: 'chuende2acc.firebasestorage.app',
    measurementId: 'G-MRWLG3V8JW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKHNfXvOIe8E7mDaGwgesUNpI8hdUW_6Q',
    appId: '1:1075523292633:android:103e12e49ea4c8ac9e5dc8',
    messagingSenderId: '1075523292633',
    projectId: 'chuende2acc',
    storageBucket: 'chuende2acc.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZUJY-FE7peeFIpCWAxEsLQlzcMEdRc_o',
    appId: '1:1075523292633:web:32dec02517ef24b69e5dc8',
    messagingSenderId: '1075523292633',
    projectId: 'chuende2acc',
    authDomain: 'chuende2acc.firebaseapp.com',
    storageBucket: 'chuende2acc.firebasestorage.app',
    measurementId: 'G-P60NLPZXSZ',
  );
}
